M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 26 Nov 2022 02:15:55 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-26T14:15:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0205
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X2.2106Y-5.1102
X2.5059Y-5.1102
T2
X2.063Y-4.9606
X2.1024Y-2.3327
X2.6535Y-4.9606
T0
M30
